<?php

namespace AppBundle\Repository;

/**
 * ContatosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContatosRepository extends \Doctrine\ORM\EntityRepository
{
}
