<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFwuc4kx\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFwuc4kx/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerFwuc4kx.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerFwuc4kx\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerFwuc4kx\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Fwuc4kx',
    'container.build_id' => '5ecfd735',
    'container.build_time' => 1557387843,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerFwuc4kx');
