<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAy8i9kr\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAy8i9kr/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerAy8i9kr.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerAy8i9kr\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerAy8i9kr\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Ay8i9kr',
    'container.build_id' => '4d85d62e',
    'container.build_time' => 1557392504,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerAy8i9kr');
