<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKkoqxcf\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKkoqxcf/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerKkoqxcf.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerKkoqxcf\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerKkoqxcf\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Kkoqxcf',
    'container.build_id' => '2ccfedd0',
    'container.build_time' => 1557497644,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerKkoqxcf');
